services:
  notification-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
      - mailhog
    networks:
      - pasantias-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025"
      - "8026:8025"
    networks:
      - pasantias-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - pasantias-network

networks:
  pasantias-network:
    external: true
    name: script_bd_pasantias-network
